package com.dxjr.portal.transfer.mapper;

import com.dxjr.portal.transfer.entity.Etransfer;

public interface EtransferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_transfer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_transfer
     *
     * @mbggenerated
     */
    int insert(Etransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_transfer
     *
     * @mbggenerated
     */
    int insertSelective(Etransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_transfer
     *
     * @mbggenerated
     */
    Etransfer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_transfer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Etransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_transfer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Etransfer record);

    Etransfer selectByTransferId(Integer transferId);
}