package com.dxjr.portal.borrow.entity;

import java.util.ArrayList;
import java.util.List;

public class BorrowApprovedExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rocky_borrow_approved
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rocky_borrow_approved
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rocky_borrow_approved
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_borrow_approved
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    public BorrowApprovedExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_borrow_approved
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_borrow_approved
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_borrow_approved
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_borrow_approved
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_borrow_approved
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_borrow_approved
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_borrow_approved
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_borrow_approved
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_borrow_approved
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_borrow_approved
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rocky_borrow_approved
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBorrowIdIsNull() {
            addCriterion("BORROW_ID is null");
            return (Criteria) this;
        }

        public Criteria andBorrowIdIsNotNull() {
            addCriterion("BORROW_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBorrowIdEqualTo(Integer value) {
            addCriterion("BORROW_ID =", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdNotEqualTo(Integer value) {
            addCriterion("BORROW_ID <>", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdGreaterThan(Integer value) {
            addCriterion("BORROW_ID >", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("BORROW_ID >=", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdLessThan(Integer value) {
            addCriterion("BORROW_ID <", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdLessThanOrEqualTo(Integer value) {
            addCriterion("BORROW_ID <=", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdIn(List<Integer> values) {
            addCriterion("BORROW_ID in", values, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdNotIn(List<Integer> values) {
            addCriterion("BORROW_ID not in", values, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdBetween(Integer value1, Integer value2) {
            addCriterion("BORROW_ID between", value1, value2, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdNotBetween(Integer value1, Integer value2) {
            addCriterion("BORROW_ID not between", value1, value2, "borrowId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andVerifyUserIsNull() {
            addCriterion("VERIFY_USER is null");
            return (Criteria) this;
        }

        public Criteria andVerifyUserIsNotNull() {
            addCriterion("VERIFY_USER is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyUserEqualTo(Integer value) {
            addCriterion("VERIFY_USER =", value, "verifyUser");
            return (Criteria) this;
        }

        public Criteria andVerifyUserNotEqualTo(Integer value) {
            addCriterion("VERIFY_USER <>", value, "verifyUser");
            return (Criteria) this;
        }

        public Criteria andVerifyUserGreaterThan(Integer value) {
            addCriterion("VERIFY_USER >", value, "verifyUser");
            return (Criteria) this;
        }

        public Criteria andVerifyUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERIFY_USER >=", value, "verifyUser");
            return (Criteria) this;
        }

        public Criteria andVerifyUserLessThan(Integer value) {
            addCriterion("VERIFY_USER <", value, "verifyUser");
            return (Criteria) this;
        }

        public Criteria andVerifyUserLessThanOrEqualTo(Integer value) {
            addCriterion("VERIFY_USER <=", value, "verifyUser");
            return (Criteria) this;
        }

        public Criteria andVerifyUserIn(List<Integer> values) {
            addCriterion("VERIFY_USER in", values, "verifyUser");
            return (Criteria) this;
        }

        public Criteria andVerifyUserNotIn(List<Integer> values) {
            addCriterion("VERIFY_USER not in", values, "verifyUser");
            return (Criteria) this;
        }

        public Criteria andVerifyUserBetween(Integer value1, Integer value2) {
            addCriterion("VERIFY_USER between", value1, value2, "verifyUser");
            return (Criteria) this;
        }

        public Criteria andVerifyUserNotBetween(Integer value1, Integer value2) {
            addCriterion("VERIFY_USER not between", value1, value2, "verifyUser");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeIsNull() {
            addCriterion("VERIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeIsNotNull() {
            addCriterion("VERIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeEqualTo(String value) {
            addCriterion("VERIFY_TIME =", value, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeNotEqualTo(String value) {
            addCriterion("VERIFY_TIME <>", value, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeGreaterThan(String value) {
            addCriterion("VERIFY_TIME >", value, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeGreaterThanOrEqualTo(String value) {
            addCriterion("VERIFY_TIME >=", value, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeLessThan(String value) {
            addCriterion("VERIFY_TIME <", value, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeLessThanOrEqualTo(String value) {
            addCriterion("VERIFY_TIME <=", value, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeLike(String value) {
            addCriterion("VERIFY_TIME like", value, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeNotLike(String value) {
            addCriterion("VERIFY_TIME not like", value, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeIn(List<String> values) {
            addCriterion("VERIFY_TIME in", values, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeNotIn(List<String> values) {
            addCriterion("VERIFY_TIME not in", values, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeBetween(String value1, String value2) {
            addCriterion("VERIFY_TIME between", value1, value2, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeNotBetween(String value1, String value2) {
            addCriterion("VERIFY_TIME not between", value1, value2, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyRemarkIsNull() {
            addCriterion("VERIFY_REMARK is null");
            return (Criteria) this;
        }

        public Criteria andVerifyRemarkIsNotNull() {
            addCriterion("VERIFY_REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyRemarkEqualTo(String value) {
            addCriterion("VERIFY_REMARK =", value, "verifyRemark");
            return (Criteria) this;
        }

        public Criteria andVerifyRemarkNotEqualTo(String value) {
            addCriterion("VERIFY_REMARK <>", value, "verifyRemark");
            return (Criteria) this;
        }

        public Criteria andVerifyRemarkGreaterThan(String value) {
            addCriterion("VERIFY_REMARK >", value, "verifyRemark");
            return (Criteria) this;
        }

        public Criteria andVerifyRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("VERIFY_REMARK >=", value, "verifyRemark");
            return (Criteria) this;
        }

        public Criteria andVerifyRemarkLessThan(String value) {
            addCriterion("VERIFY_REMARK <", value, "verifyRemark");
            return (Criteria) this;
        }

        public Criteria andVerifyRemarkLessThanOrEqualTo(String value) {
            addCriterion("VERIFY_REMARK <=", value, "verifyRemark");
            return (Criteria) this;
        }

        public Criteria andVerifyRemarkLike(String value) {
            addCriterion("VERIFY_REMARK like", value, "verifyRemark");
            return (Criteria) this;
        }

        public Criteria andVerifyRemarkNotLike(String value) {
            addCriterion("VERIFY_REMARK not like", value, "verifyRemark");
            return (Criteria) this;
        }

        public Criteria andVerifyRemarkIn(List<String> values) {
            addCriterion("VERIFY_REMARK in", values, "verifyRemark");
            return (Criteria) this;
        }

        public Criteria andVerifyRemarkNotIn(List<String> values) {
            addCriterion("VERIFY_REMARK not in", values, "verifyRemark");
            return (Criteria) this;
        }

        public Criteria andVerifyRemarkBetween(String value1, String value2) {
            addCriterion("VERIFY_REMARK between", value1, value2, "verifyRemark");
            return (Criteria) this;
        }

        public Criteria andVerifyRemarkNotBetween(String value1, String value2) {
            addCriterion("VERIFY_REMARK not between", value1, value2, "verifyRemark");
            return (Criteria) this;
        }

        public Criteria andVerifyUser2IsNull() {
            addCriterion("VERIFY_USER2 is null");
            return (Criteria) this;
        }

        public Criteria andVerifyUser2IsNotNull() {
            addCriterion("VERIFY_USER2 is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyUser2EqualTo(Integer value) {
            addCriterion("VERIFY_USER2 =", value, "verifyUser2");
            return (Criteria) this;
        }

        public Criteria andVerifyUser2NotEqualTo(Integer value) {
            addCriterion("VERIFY_USER2 <>", value, "verifyUser2");
            return (Criteria) this;
        }

        public Criteria andVerifyUser2GreaterThan(Integer value) {
            addCriterion("VERIFY_USER2 >", value, "verifyUser2");
            return (Criteria) this;
        }

        public Criteria andVerifyUser2GreaterThanOrEqualTo(Integer value) {
            addCriterion("VERIFY_USER2 >=", value, "verifyUser2");
            return (Criteria) this;
        }

        public Criteria andVerifyUser2LessThan(Integer value) {
            addCriterion("VERIFY_USER2 <", value, "verifyUser2");
            return (Criteria) this;
        }

        public Criteria andVerifyUser2LessThanOrEqualTo(Integer value) {
            addCriterion("VERIFY_USER2 <=", value, "verifyUser2");
            return (Criteria) this;
        }

        public Criteria andVerifyUser2In(List<Integer> values) {
            addCriterion("VERIFY_USER2 in", values, "verifyUser2");
            return (Criteria) this;
        }

        public Criteria andVerifyUser2NotIn(List<Integer> values) {
            addCriterion("VERIFY_USER2 not in", values, "verifyUser2");
            return (Criteria) this;
        }

        public Criteria andVerifyUser2Between(Integer value1, Integer value2) {
            addCriterion("VERIFY_USER2 between", value1, value2, "verifyUser2");
            return (Criteria) this;
        }

        public Criteria andVerifyUser2NotBetween(Integer value1, Integer value2) {
            addCriterion("VERIFY_USER2 not between", value1, value2, "verifyUser2");
            return (Criteria) this;
        }

        public Criteria andVerifyTime2IsNull() {
            addCriterion("VERIFY_TIME2 is null");
            return (Criteria) this;
        }

        public Criteria andVerifyTime2IsNotNull() {
            addCriterion("VERIFY_TIME2 is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyTime2EqualTo(String value) {
            addCriterion("VERIFY_TIME2 =", value, "verifyTime2");
            return (Criteria) this;
        }

        public Criteria andVerifyTime2NotEqualTo(String value) {
            addCriterion("VERIFY_TIME2 <>", value, "verifyTime2");
            return (Criteria) this;
        }

        public Criteria andVerifyTime2GreaterThan(String value) {
            addCriterion("VERIFY_TIME2 >", value, "verifyTime2");
            return (Criteria) this;
        }

        public Criteria andVerifyTime2GreaterThanOrEqualTo(String value) {
            addCriterion("VERIFY_TIME2 >=", value, "verifyTime2");
            return (Criteria) this;
        }

        public Criteria andVerifyTime2LessThan(String value) {
            addCriterion("VERIFY_TIME2 <", value, "verifyTime2");
            return (Criteria) this;
        }

        public Criteria andVerifyTime2LessThanOrEqualTo(String value) {
            addCriterion("VERIFY_TIME2 <=", value, "verifyTime2");
            return (Criteria) this;
        }

        public Criteria andVerifyTime2Like(String value) {
            addCriterion("VERIFY_TIME2 like", value, "verifyTime2");
            return (Criteria) this;
        }

        public Criteria andVerifyTime2NotLike(String value) {
            addCriterion("VERIFY_TIME2 not like", value, "verifyTime2");
            return (Criteria) this;
        }

        public Criteria andVerifyTime2In(List<String> values) {
            addCriterion("VERIFY_TIME2 in", values, "verifyTime2");
            return (Criteria) this;
        }

        public Criteria andVerifyTime2NotIn(List<String> values) {
            addCriterion("VERIFY_TIME2 not in", values, "verifyTime2");
            return (Criteria) this;
        }

        public Criteria andVerifyTime2Between(String value1, String value2) {
            addCriterion("VERIFY_TIME2 between", value1, value2, "verifyTime2");
            return (Criteria) this;
        }

        public Criteria andVerifyTime2NotBetween(String value1, String value2) {
            addCriterion("VERIFY_TIME2 not between", value1, value2, "verifyTime2");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark2IsNull() {
            addCriterion("VERIFY_REMARK2 is null");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark2IsNotNull() {
            addCriterion("VERIFY_REMARK2 is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark2EqualTo(String value) {
            addCriterion("VERIFY_REMARK2 =", value, "verifyRemark2");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark2NotEqualTo(String value) {
            addCriterion("VERIFY_REMARK2 <>", value, "verifyRemark2");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark2GreaterThan(String value) {
            addCriterion("VERIFY_REMARK2 >", value, "verifyRemark2");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark2GreaterThanOrEqualTo(String value) {
            addCriterion("VERIFY_REMARK2 >=", value, "verifyRemark2");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark2LessThan(String value) {
            addCriterion("VERIFY_REMARK2 <", value, "verifyRemark2");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark2LessThanOrEqualTo(String value) {
            addCriterion("VERIFY_REMARK2 <=", value, "verifyRemark2");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark2Like(String value) {
            addCriterion("VERIFY_REMARK2 like", value, "verifyRemark2");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark2NotLike(String value) {
            addCriterion("VERIFY_REMARK2 not like", value, "verifyRemark2");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark2In(List<String> values) {
            addCriterion("VERIFY_REMARK2 in", values, "verifyRemark2");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark2NotIn(List<String> values) {
            addCriterion("VERIFY_REMARK2 not in", values, "verifyRemark2");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark2Between(String value1, String value2) {
            addCriterion("VERIFY_REMARK2 between", value1, value2, "verifyRemark2");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark2NotBetween(String value1, String value2) {
            addCriterion("VERIFY_REMARK2 not between", value1, value2, "verifyRemark2");
            return (Criteria) this;
        }

        public Criteria andVerifyUser3IsNull() {
            addCriterion("VERIFY_USER3 is null");
            return (Criteria) this;
        }

        public Criteria andVerifyUser3IsNotNull() {
            addCriterion("VERIFY_USER3 is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyUser3EqualTo(Integer value) {
            addCriterion("VERIFY_USER3 =", value, "verifyUser3");
            return (Criteria) this;
        }

        public Criteria andVerifyUser3NotEqualTo(Integer value) {
            addCriterion("VERIFY_USER3 <>", value, "verifyUser3");
            return (Criteria) this;
        }

        public Criteria andVerifyUser3GreaterThan(Integer value) {
            addCriterion("VERIFY_USER3 >", value, "verifyUser3");
            return (Criteria) this;
        }

        public Criteria andVerifyUser3GreaterThanOrEqualTo(Integer value) {
            addCriterion("VERIFY_USER3 >=", value, "verifyUser3");
            return (Criteria) this;
        }

        public Criteria andVerifyUser3LessThan(Integer value) {
            addCriterion("VERIFY_USER3 <", value, "verifyUser3");
            return (Criteria) this;
        }

        public Criteria andVerifyUser3LessThanOrEqualTo(Integer value) {
            addCriterion("VERIFY_USER3 <=", value, "verifyUser3");
            return (Criteria) this;
        }

        public Criteria andVerifyUser3In(List<Integer> values) {
            addCriterion("VERIFY_USER3 in", values, "verifyUser3");
            return (Criteria) this;
        }

        public Criteria andVerifyUser3NotIn(List<Integer> values) {
            addCriterion("VERIFY_USER3 not in", values, "verifyUser3");
            return (Criteria) this;
        }

        public Criteria andVerifyUser3Between(Integer value1, Integer value2) {
            addCriterion("VERIFY_USER3 between", value1, value2, "verifyUser3");
            return (Criteria) this;
        }

        public Criteria andVerifyUser3NotBetween(Integer value1, Integer value2) {
            addCriterion("VERIFY_USER3 not between", value1, value2, "verifyUser3");
            return (Criteria) this;
        }

        public Criteria andVerifyTime3IsNull() {
            addCriterion("VERIFY_TIME3 is null");
            return (Criteria) this;
        }

        public Criteria andVerifyTime3IsNotNull() {
            addCriterion("VERIFY_TIME3 is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyTime3EqualTo(String value) {
            addCriterion("VERIFY_TIME3 =", value, "verifyTime3");
            return (Criteria) this;
        }

        public Criteria andVerifyTime3NotEqualTo(String value) {
            addCriterion("VERIFY_TIME3 <>", value, "verifyTime3");
            return (Criteria) this;
        }

        public Criteria andVerifyTime3GreaterThan(String value) {
            addCriterion("VERIFY_TIME3 >", value, "verifyTime3");
            return (Criteria) this;
        }

        public Criteria andVerifyTime3GreaterThanOrEqualTo(String value) {
            addCriterion("VERIFY_TIME3 >=", value, "verifyTime3");
            return (Criteria) this;
        }

        public Criteria andVerifyTime3LessThan(String value) {
            addCriterion("VERIFY_TIME3 <", value, "verifyTime3");
            return (Criteria) this;
        }

        public Criteria andVerifyTime3LessThanOrEqualTo(String value) {
            addCriterion("VERIFY_TIME3 <=", value, "verifyTime3");
            return (Criteria) this;
        }

        public Criteria andVerifyTime3Like(String value) {
            addCriterion("VERIFY_TIME3 like", value, "verifyTime3");
            return (Criteria) this;
        }

        public Criteria andVerifyTime3NotLike(String value) {
            addCriterion("VERIFY_TIME3 not like", value, "verifyTime3");
            return (Criteria) this;
        }

        public Criteria andVerifyTime3In(List<String> values) {
            addCriterion("VERIFY_TIME3 in", values, "verifyTime3");
            return (Criteria) this;
        }

        public Criteria andVerifyTime3NotIn(List<String> values) {
            addCriterion("VERIFY_TIME3 not in", values, "verifyTime3");
            return (Criteria) this;
        }

        public Criteria andVerifyTime3Between(String value1, String value2) {
            addCriterion("VERIFY_TIME3 between", value1, value2, "verifyTime3");
            return (Criteria) this;
        }

        public Criteria andVerifyTime3NotBetween(String value1, String value2) {
            addCriterion("VERIFY_TIME3 not between", value1, value2, "verifyTime3");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark3IsNull() {
            addCriterion("VERIFY_REMARK3 is null");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark3IsNotNull() {
            addCriterion("VERIFY_REMARK3 is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark3EqualTo(String value) {
            addCriterion("VERIFY_REMARK3 =", value, "verifyRemark3");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark3NotEqualTo(String value) {
            addCriterion("VERIFY_REMARK3 <>", value, "verifyRemark3");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark3GreaterThan(String value) {
            addCriterion("VERIFY_REMARK3 >", value, "verifyRemark3");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark3GreaterThanOrEqualTo(String value) {
            addCriterion("VERIFY_REMARK3 >=", value, "verifyRemark3");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark3LessThan(String value) {
            addCriterion("VERIFY_REMARK3 <", value, "verifyRemark3");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark3LessThanOrEqualTo(String value) {
            addCriterion("VERIFY_REMARK3 <=", value, "verifyRemark3");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark3Like(String value) {
            addCriterion("VERIFY_REMARK3 like", value, "verifyRemark3");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark3NotLike(String value) {
            addCriterion("VERIFY_REMARK3 not like", value, "verifyRemark3");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark3In(List<String> values) {
            addCriterion("VERIFY_REMARK3 in", values, "verifyRemark3");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark3NotIn(List<String> values) {
            addCriterion("VERIFY_REMARK3 not in", values, "verifyRemark3");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark3Between(String value1, String value2) {
            addCriterion("VERIFY_REMARK3 between", value1, value2, "verifyRemark3");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark3NotBetween(String value1, String value2) {
            addCriterion("VERIFY_REMARK3 not between", value1, value2, "verifyRemark3");
            return (Criteria) this;
        }

        public Criteria andVerifyUser4IsNull() {
            addCriterion("VERIFY_USER4 is null");
            return (Criteria) this;
        }

        public Criteria andVerifyUser4IsNotNull() {
            addCriterion("VERIFY_USER4 is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyUser4EqualTo(Integer value) {
            addCriterion("VERIFY_USER4 =", value, "verifyUser4");
            return (Criteria) this;
        }

        public Criteria andVerifyUser4NotEqualTo(Integer value) {
            addCriterion("VERIFY_USER4 <>", value, "verifyUser4");
            return (Criteria) this;
        }

        public Criteria andVerifyUser4GreaterThan(Integer value) {
            addCriterion("VERIFY_USER4 >", value, "verifyUser4");
            return (Criteria) this;
        }

        public Criteria andVerifyUser4GreaterThanOrEqualTo(Integer value) {
            addCriterion("VERIFY_USER4 >=", value, "verifyUser4");
            return (Criteria) this;
        }

        public Criteria andVerifyUser4LessThan(Integer value) {
            addCriterion("VERIFY_USER4 <", value, "verifyUser4");
            return (Criteria) this;
        }

        public Criteria andVerifyUser4LessThanOrEqualTo(Integer value) {
            addCriterion("VERIFY_USER4 <=", value, "verifyUser4");
            return (Criteria) this;
        }

        public Criteria andVerifyUser4In(List<Integer> values) {
            addCriterion("VERIFY_USER4 in", values, "verifyUser4");
            return (Criteria) this;
        }

        public Criteria andVerifyUser4NotIn(List<Integer> values) {
            addCriterion("VERIFY_USER4 not in", values, "verifyUser4");
            return (Criteria) this;
        }

        public Criteria andVerifyUser4Between(Integer value1, Integer value2) {
            addCriterion("VERIFY_USER4 between", value1, value2, "verifyUser4");
            return (Criteria) this;
        }

        public Criteria andVerifyUser4NotBetween(Integer value1, Integer value2) {
            addCriterion("VERIFY_USER4 not between", value1, value2, "verifyUser4");
            return (Criteria) this;
        }

        public Criteria andVerifyTime4IsNull() {
            addCriterion("VERIFY_TIME4 is null");
            return (Criteria) this;
        }

        public Criteria andVerifyTime4IsNotNull() {
            addCriterion("VERIFY_TIME4 is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyTime4EqualTo(String value) {
            addCriterion("VERIFY_TIME4 =", value, "verifyTime4");
            return (Criteria) this;
        }

        public Criteria andVerifyTime4NotEqualTo(String value) {
            addCriterion("VERIFY_TIME4 <>", value, "verifyTime4");
            return (Criteria) this;
        }

        public Criteria andVerifyTime4GreaterThan(String value) {
            addCriterion("VERIFY_TIME4 >", value, "verifyTime4");
            return (Criteria) this;
        }

        public Criteria andVerifyTime4GreaterThanOrEqualTo(String value) {
            addCriterion("VERIFY_TIME4 >=", value, "verifyTime4");
            return (Criteria) this;
        }

        public Criteria andVerifyTime4LessThan(String value) {
            addCriterion("VERIFY_TIME4 <", value, "verifyTime4");
            return (Criteria) this;
        }

        public Criteria andVerifyTime4LessThanOrEqualTo(String value) {
            addCriterion("VERIFY_TIME4 <=", value, "verifyTime4");
            return (Criteria) this;
        }

        public Criteria andVerifyTime4Like(String value) {
            addCriterion("VERIFY_TIME4 like", value, "verifyTime4");
            return (Criteria) this;
        }

        public Criteria andVerifyTime4NotLike(String value) {
            addCriterion("VERIFY_TIME4 not like", value, "verifyTime4");
            return (Criteria) this;
        }

        public Criteria andVerifyTime4In(List<String> values) {
            addCriterion("VERIFY_TIME4 in", values, "verifyTime4");
            return (Criteria) this;
        }

        public Criteria andVerifyTime4NotIn(List<String> values) {
            addCriterion("VERIFY_TIME4 not in", values, "verifyTime4");
            return (Criteria) this;
        }

        public Criteria andVerifyTime4Between(String value1, String value2) {
            addCriterion("VERIFY_TIME4 between", value1, value2, "verifyTime4");
            return (Criteria) this;
        }

        public Criteria andVerifyTime4NotBetween(String value1, String value2) {
            addCriterion("VERIFY_TIME4 not between", value1, value2, "verifyTime4");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark4IsNull() {
            addCriterion("VERIFY_REMARK4 is null");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark4IsNotNull() {
            addCriterion("VERIFY_REMARK4 is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark4EqualTo(String value) {
            addCriterion("VERIFY_REMARK4 =", value, "verifyRemark4");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark4NotEqualTo(String value) {
            addCriterion("VERIFY_REMARK4 <>", value, "verifyRemark4");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark4GreaterThan(String value) {
            addCriterion("VERIFY_REMARK4 >", value, "verifyRemark4");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark4GreaterThanOrEqualTo(String value) {
            addCriterion("VERIFY_REMARK4 >=", value, "verifyRemark4");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark4LessThan(String value) {
            addCriterion("VERIFY_REMARK4 <", value, "verifyRemark4");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark4LessThanOrEqualTo(String value) {
            addCriterion("VERIFY_REMARK4 <=", value, "verifyRemark4");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark4Like(String value) {
            addCriterion("VERIFY_REMARK4 like", value, "verifyRemark4");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark4NotLike(String value) {
            addCriterion("VERIFY_REMARK4 not like", value, "verifyRemark4");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark4In(List<String> values) {
            addCriterion("VERIFY_REMARK4 in", values, "verifyRemark4");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark4NotIn(List<String> values) {
            addCriterion("VERIFY_REMARK4 not in", values, "verifyRemark4");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark4Between(String value1, String value2) {
            addCriterion("VERIFY_REMARK4 between", value1, value2, "verifyRemark4");
            return (Criteria) this;
        }

        public Criteria andVerifyRemark4NotBetween(String value1, String value2) {
            addCriterion("VERIFY_REMARK4 not between", value1, value2, "verifyRemark4");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rocky_borrow_approved
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 22 17:15:55 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rocky_borrow_approved
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}