package com.dxjr.portal.borrow.entity;


public class BorrowApproved {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rocky_borrow_approved.ID
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rocky_borrow_approved.BORROW_ID
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    private Integer borrowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rocky_borrow_approved.STATUS
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rocky_borrow_approved.VERIFY_USER
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    private Integer verifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rocky_borrow_approved.VERIFY_TIME
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    private String verifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rocky_borrow_approved.VERIFY_REMARK
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    private String verifyRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rocky_borrow_approved.VERIFY_USER2
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    private Integer verifyUser2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rocky_borrow_approved.VERIFY_TIME2
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    private String verifyTime2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rocky_borrow_approved.VERIFY_REMARK2
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    private String verifyRemark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rocky_borrow_approved.VERIFY_USER3
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    private Integer verifyUser3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rocky_borrow_approved.VERIFY_TIME3
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    private String verifyTime3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rocky_borrow_approved.VERIFY_REMARK3
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    private String verifyRemark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rocky_borrow_approved.VERIFY_USER4
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    private Integer verifyUser4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rocky_borrow_approved.VERIFY_TIME4
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    private String verifyTime4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rocky_borrow_approved.VERIFY_REMARK4
     *
     * @mbggenerated Tue Apr 22 17:15:55 CST 2014
     */
    private String verifyRemark4;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getBorrowId() {
		return borrowId;
	}

	public void setBorrowId(Integer borrowId) {
		this.borrowId = borrowId;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getVerifyUser() {
		return verifyUser;
	}

	public void setVerifyUser(Integer verifyUser) {
		this.verifyUser = verifyUser;
	}

	public String getVerifyTime() {
		return verifyTime;
	}

	public void setVerifyTime(String verifyTime) {
		this.verifyTime = verifyTime;
	}

	public String getVerifyRemark() {
		return verifyRemark;
	}

	public void setVerifyRemark(String verifyRemark) {
		this.verifyRemark = verifyRemark;
	}

	public Integer getVerifyUser2() {
		return verifyUser2;
	}

	public void setVerifyUser2(Integer verifyUser2) {
		this.verifyUser2 = verifyUser2;
	}

	public String getVerifyTime2() {
		return verifyTime2;
	}

	public void setVerifyTime2(String verifyTime2) {
		this.verifyTime2 = verifyTime2;
	}

	public String getVerifyRemark2() {
		return verifyRemark2;
	}

	public void setVerifyRemark2(String verifyRemark2) {
		this.verifyRemark2 = verifyRemark2;
	}

	public Integer getVerifyUser3() {
		return verifyUser3;
	}

	public void setVerifyUser3(Integer verifyUser3) {
		this.verifyUser3 = verifyUser3;
	}

	public String getVerifyTime3() {
		return verifyTime3;
	}

	public void setVerifyTime3(String verifyTime3) {
		this.verifyTime3 = verifyTime3;
	}

	public String getVerifyRemark3() {
		return verifyRemark3;
	}

	public void setVerifyRemark3(String verifyRemark3) {
		this.verifyRemark3 = verifyRemark3;
	}

	public Integer getVerifyUser4() {
		return verifyUser4;
	}

	public void setVerifyUser4(Integer verifyUser4) {
		this.verifyUser4 = verifyUser4;
	}

	public String getVerifyTime4() {
		return verifyTime4;
	}

	public void setVerifyTime4(String verifyTime4) {
		this.verifyTime4 = verifyTime4;
	}

	public String getVerifyRemark4() {
		return verifyRemark4;
	}

	public void setVerifyRemark4(String verifyRemark4) {
		this.verifyRemark4 = verifyRemark4;
	}

	@Override
	public String toString() {
		return "BorrowApproved [id=" + id + ", borrowId=" + borrowId
				+ ", status=" + status + ", verifyUser=" + verifyUser
				+ ", verifyTime=" + verifyTime + ", verifyRemark="
				+ verifyRemark + ", verifyUser2=" + verifyUser2
				+ ", verifyTime2=" + verifyTime2 + ", verifyRemark2="
				+ verifyRemark2 + ", verifyUser3=" + verifyUser3
				+ ", verifyTime3=" + verifyTime3 + ", verifyRemark3="
				+ verifyRemark3 + ", verifyUser4=" + verifyUser4
				+ ", verifyTime4=" + verifyTime4 + ", verifyRemark4="
				+ verifyRemark4 + "]";
	}

    
}