package com.dxjr.portal.borrow.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RepaymentRecord {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column rocky_b_repaymentrecord.ID
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column rocky_b_repaymentrecord.STATUS
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	private Integer status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column rocky_b_repaymentrecord.WEBSTATUS
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	private Integer webstatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column rocky_b_repaymentrecord.ORDER
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	private Integer order;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column rocky_b_repaymentrecord.BORROW_ID
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	private Integer borrowId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column rocky_b_repaymentrecord.REPAYMENT_TIME
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	private String repaymentTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column rocky_b_repaymentrecord.REPAYMENT_YESTIME
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	private String repaymentYestime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column rocky_b_repaymentrecord.REPAYMENT_ACCOUNT
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	private BigDecimal repaymentAccount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column rocky_b_repaymentrecord.REPAYMENT_YESACCOUNT
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	private BigDecimal repaymentYesaccount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column rocky_b_repaymentrecord.LATE_DAYS
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	private Integer lateDays;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column rocky_b_repaymentrecord.LATE_INTEREST
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	private BigDecimal lateInterest;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column rocky_b_repaymentrecord.INTEREST
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	private BigDecimal interest;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column rocky_b_repaymentrecord.CAPITAL
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	private BigDecimal capital;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column rocky_b_repaymentrecord.ADDTIME
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	private String addtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column rocky_b_repaymentrecord.ADDIP
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	private String addip;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column rocky_b_repaymentrecord.USER_ID
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column rocky_b_repaymentrecord.ADVANCETIME
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	private Date advancetime;

	private String name;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column rocky_b_repaymentrecord.ID
	 * 
	 * @return the value of rocky_b_repaymentrecord.ID
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column rocky_b_repaymentrecord.ID
	 * 
	 * @param id
	 *            the value for rocky_b_repaymentrecord.ID
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column rocky_b_repaymentrecord.STATUS
	 * 
	 * @return the value of rocky_b_repaymentrecord.STATUS
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column rocky_b_repaymentrecord.STATUS
	 * 
	 * @param status
	 *            the value for rocky_b_repaymentrecord.STATUS
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column rocky_b_repaymentrecord.WEBSTATUS
	 * 
	 * @return the value of rocky_b_repaymentrecord.WEBSTATUS
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public Integer getWebstatus() {
		return webstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column rocky_b_repaymentrecord.WEBSTATUS
	 * 
	 * @param webstatus
	 *            the value for rocky_b_repaymentrecord.WEBSTATUS
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public void setWebstatus(Integer webstatus) {
		this.webstatus = webstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column rocky_b_repaymentrecord.ORDER
	 * 
	 * @return the value of rocky_b_repaymentrecord.ORDER
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public Integer getOrder() {
		return order;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column rocky_b_repaymentrecord.ORDER
	 * 
	 * @param order
	 *            the value for rocky_b_repaymentrecord.ORDER
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public void setOrder(Integer order) {
		this.order = order;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column rocky_b_repaymentrecord.BORROW_ID
	 * 
	 * @return the value of rocky_b_repaymentrecord.BORROW_ID
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public Integer getBorrowId() {
		return borrowId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column rocky_b_repaymentrecord.BORROW_ID
	 * 
	 * @param borrowId
	 *            the value for rocky_b_repaymentrecord.BORROW_ID
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public void setBorrowId(Integer borrowId) {
		this.borrowId = borrowId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column rocky_b_repaymentrecord.REPAYMENT_TIME
	 * 
	 * @return the value of rocky_b_repaymentrecord.REPAYMENT_TIME
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public String getRepaymentTime() {
		return repaymentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column rocky_b_repaymentrecord.REPAYMENT_TIME
	 * 
	 * @param repaymentTime
	 *            the value for rocky_b_repaymentrecord.REPAYMENT_TIME
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public void setRepaymentTime(String repaymentTime) {
		this.repaymentTime = repaymentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column rocky_b_repaymentrecord.REPAYMENT_YESTIME
	 * 
	 * @return the value of rocky_b_repaymentrecord.REPAYMENT_YESTIME
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public String getRepaymentYestime() {
		return repaymentYestime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column rocky_b_repaymentrecord.REPAYMENT_YESTIME
	 * 
	 * @param repaymentYestime
	 *            the value for rocky_b_repaymentrecord.REPAYMENT_YESTIME
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public void setRepaymentYestime(String repaymentYestime) {
		this.repaymentYestime = repaymentYestime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column rocky_b_repaymentrecord.REPAYMENT_ACCOUNT
	 * 
	 * @return the value of rocky_b_repaymentrecord.REPAYMENT_ACCOUNT
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public BigDecimal getRepaymentAccount() {
		return repaymentAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column rocky_b_repaymentrecord.REPAYMENT_ACCOUNT
	 * 
	 * @param repaymentAccount
	 *            the value for rocky_b_repaymentrecord.REPAYMENT_ACCOUNT
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public void setRepaymentAccount(BigDecimal repaymentAccount) {
		this.repaymentAccount = repaymentAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column rocky_b_repaymentrecord.REPAYMENT_YESACCOUNT
	 * 
	 * @return the value of rocky_b_repaymentrecord.REPAYMENT_YESACCOUNT
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public BigDecimal getRepaymentYesaccount() {
		return repaymentYesaccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column rocky_b_repaymentrecord.REPAYMENT_YESACCOUNT
	 * 
	 * @param repaymentYesaccount
	 *            the value for rocky_b_repaymentrecord.REPAYMENT_YESACCOUNT
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public void setRepaymentYesaccount(BigDecimal repaymentYesaccount) {
		this.repaymentYesaccount = repaymentYesaccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column rocky_b_repaymentrecord.LATE_DAYS
	 * 
	 * @return the value of rocky_b_repaymentrecord.LATE_DAYS
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public Integer getLateDays() {
		return lateDays;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column rocky_b_repaymentrecord.LATE_DAYS
	 * 
	 * @param lateDays
	 *            the value for rocky_b_repaymentrecord.LATE_DAYS
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public void setLateDays(Integer lateDays) {
		this.lateDays = lateDays;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column rocky_b_repaymentrecord.LATE_INTEREST
	 * 
	 * @return the value of rocky_b_repaymentrecord.LATE_INTEREST
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public BigDecimal getLateInterest() {
		return lateInterest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column rocky_b_repaymentrecord.LATE_INTEREST
	 * 
	 * @param lateInterest
	 *            the value for rocky_b_repaymentrecord.LATE_INTEREST
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public void setLateInterest(BigDecimal lateInterest) {
		this.lateInterest = lateInterest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column rocky_b_repaymentrecord.INTEREST
	 * 
	 * @return the value of rocky_b_repaymentrecord.INTEREST
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public BigDecimal getInterest() {
		return interest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column rocky_b_repaymentrecord.INTEREST
	 * 
	 * @param interest
	 *            the value for rocky_b_repaymentrecord.INTEREST
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public void setInterest(BigDecimal interest) {
		this.interest = interest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column rocky_b_repaymentrecord.CAPITAL
	 * 
	 * @return the value of rocky_b_repaymentrecord.CAPITAL
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public BigDecimal getCapital() {
		return capital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column rocky_b_repaymentrecord.CAPITAL
	 * 
	 * @param capital
	 *            the value for rocky_b_repaymentrecord.CAPITAL
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public void setCapital(BigDecimal capital) {
		this.capital = capital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column rocky_b_repaymentrecord.ADDTIME
	 * 
	 * @return the value of rocky_b_repaymentrecord.ADDTIME
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public String getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column rocky_b_repaymentrecord.ADDTIME
	 * 
	 * @param addtime
	 *            the value for rocky_b_repaymentrecord.ADDTIME
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public void setAddtime(String addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column rocky_b_repaymentrecord.ADDIP
	 * 
	 * @return the value of rocky_b_repaymentrecord.ADDIP
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public String getAddip() {
		return addip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column rocky_b_repaymentrecord.ADDIP
	 * 
	 * @param addip
	 *            the value for rocky_b_repaymentrecord.ADDIP
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public void setAddip(String addip) {
		this.addip = addip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column rocky_b_repaymentrecord.USER_ID
	 * 
	 * @return the value of rocky_b_repaymentrecord.USER_ID
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column rocky_b_repaymentrecord.USER_ID
	 * 
	 * @param userId
	 *            the value for rocky_b_repaymentrecord.USER_ID
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column rocky_b_repaymentrecord.ADVANCETIME
	 * 
	 * @return the value of rocky_b_repaymentrecord.ADVANCETIME
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public Date getAdvancetime() {
		return advancetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column rocky_b_repaymentrecord.ADVANCETIME
	 * 
	 * @param advancetime
	 *            the value for rocky_b_repaymentrecord.ADVANCETIME
	 * 
	 * @mbggenerated Wed Jun 18 09:20:22 CST 2014
	 */
	public void setAdvancetime(Date advancetime) {
		this.advancetime = advancetime;
	}
}