package com.dxjr.portal.borrow.entity;

import java.util.ArrayList;
import java.util.List;

public class TenderRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rocky_b_tenderrecord
     *
     * @mbggenerated Mon May 19 14:13:32 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rocky_b_tenderrecord
     *
     * @mbggenerated Mon May 19 14:13:32 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rocky_b_tenderrecord
     *
     * @mbggenerated Mon May 19 14:13:32 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_b_tenderrecord
     *
     * @mbggenerated Mon May 19 14:13:32 CST 2014
     */
    public TenderRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_b_tenderrecord
     *
     * @mbggenerated Mon May 19 14:13:32 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_b_tenderrecord
     *
     * @mbggenerated Mon May 19 14:13:32 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_b_tenderrecord
     *
     * @mbggenerated Mon May 19 14:13:32 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_b_tenderrecord
     *
     * @mbggenerated Mon May 19 14:13:32 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_b_tenderrecord
     *
     * @mbggenerated Mon May 19 14:13:32 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_b_tenderrecord
     *
     * @mbggenerated Mon May 19 14:13:32 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_b_tenderrecord
     *
     * @mbggenerated Mon May 19 14:13:32 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_b_tenderrecord
     *
     * @mbggenerated Mon May 19 14:13:32 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_b_tenderrecord
     *
     * @mbggenerated Mon May 19 14:13:32 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rocky_b_tenderrecord
     *
     * @mbggenerated Mon May 19 14:13:32 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rocky_b_tenderrecord
     *
     * @mbggenerated Mon May 19 14:13:32 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdIsNull() {
            addCriterion("BORROW_ID is null");
            return (Criteria) this;
        }

        public Criteria andBorrowIdIsNotNull() {
            addCriterion("BORROW_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBorrowIdEqualTo(Integer value) {
            addCriterion("BORROW_ID =", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdNotEqualTo(Integer value) {
            addCriterion("BORROW_ID <>", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdGreaterThan(Integer value) {
            addCriterion("BORROW_ID >", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("BORROW_ID >=", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdLessThan(Integer value) {
            addCriterion("BORROW_ID <", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdLessThanOrEqualTo(Integer value) {
            addCriterion("BORROW_ID <=", value, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdIn(List<Integer> values) {
            addCriterion("BORROW_ID in", values, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdNotIn(List<Integer> values) {
            addCriterion("BORROW_ID not in", values, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdBetween(Integer value1, Integer value2) {
            addCriterion("BORROW_ID between", value1, value2, "borrowId");
            return (Criteria) this;
        }

        public Criteria andBorrowIdNotBetween(Integer value1, Integer value2) {
            addCriterion("BORROW_ID not between", value1, value2, "borrowId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andAccountIsNull() {
            addCriterion("ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andAccountIsNotNull() {
            addCriterion("ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andAccountEqualTo(Double value) {
            addCriterion("ACCOUNT =", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotEqualTo(Double value) {
            addCriterion("ACCOUNT <>", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThan(Double value) {
            addCriterion("ACCOUNT >", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThanOrEqualTo(Double value) {
            addCriterion("ACCOUNT >=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThan(Double value) {
            addCriterion("ACCOUNT <", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThanOrEqualTo(Double value) {
            addCriterion("ACCOUNT <=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountIn(List<Double> values) {
            addCriterion("ACCOUNT in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotIn(List<Double> values) {
            addCriterion("ACCOUNT not in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountBetween(Double value1, Double value2) {
            addCriterion("ACCOUNT between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotBetween(Double value1, Double value2) {
            addCriterion("ACCOUNT not between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andInterestIsNull() {
            addCriterion("INTEREST is null");
            return (Criteria) this;
        }

        public Criteria andInterestIsNotNull() {
            addCriterion("INTEREST is not null");
            return (Criteria) this;
        }

        public Criteria andInterestEqualTo(Double value) {
            addCriterion("INTEREST =", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotEqualTo(Double value) {
            addCriterion("INTEREST <>", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThan(Double value) {
            addCriterion("INTEREST >", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThanOrEqualTo(Double value) {
            addCriterion("INTEREST >=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThan(Double value) {
            addCriterion("INTEREST <", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThanOrEqualTo(Double value) {
            addCriterion("INTEREST <=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestIn(List<Double> values) {
            addCriterion("INTEREST in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotIn(List<Double> values) {
            addCriterion("INTEREST not in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestBetween(Double value1, Double value2) {
            addCriterion("INTEREST between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotBetween(Double value1, Double value2) {
            addCriterion("INTEREST not between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andRepaymentAccountIsNull() {
            addCriterion("REPAYMENT_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andRepaymentAccountIsNotNull() {
            addCriterion("REPAYMENT_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andRepaymentAccountEqualTo(Double value) {
            addCriterion("REPAYMENT_ACCOUNT =", value, "repaymentAccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentAccountNotEqualTo(Double value) {
            addCriterion("REPAYMENT_ACCOUNT <>", value, "repaymentAccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentAccountGreaterThan(Double value) {
            addCriterion("REPAYMENT_ACCOUNT >", value, "repaymentAccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentAccountGreaterThanOrEqualTo(Double value) {
            addCriterion("REPAYMENT_ACCOUNT >=", value, "repaymentAccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentAccountLessThan(Double value) {
            addCriterion("REPAYMENT_ACCOUNT <", value, "repaymentAccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentAccountLessThanOrEqualTo(Double value) {
            addCriterion("REPAYMENT_ACCOUNT <=", value, "repaymentAccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentAccountIn(List<Double> values) {
            addCriterion("REPAYMENT_ACCOUNT in", values, "repaymentAccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentAccountNotIn(List<Double> values) {
            addCriterion("REPAYMENT_ACCOUNT not in", values, "repaymentAccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentAccountBetween(Double value1, Double value2) {
            addCriterion("REPAYMENT_ACCOUNT between", value1, value2, "repaymentAccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentAccountNotBetween(Double value1, Double value2) {
            addCriterion("REPAYMENT_ACCOUNT not between", value1, value2, "repaymentAccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesaccountIsNull() {
            addCriterion("REPAYMENT_YESACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesaccountIsNotNull() {
            addCriterion("REPAYMENT_YESACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesaccountEqualTo(Double value) {
            addCriterion("REPAYMENT_YESACCOUNT =", value, "repaymentYesaccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesaccountNotEqualTo(Double value) {
            addCriterion("REPAYMENT_YESACCOUNT <>", value, "repaymentYesaccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesaccountGreaterThan(Double value) {
            addCriterion("REPAYMENT_YESACCOUNT >", value, "repaymentYesaccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesaccountGreaterThanOrEqualTo(Double value) {
            addCriterion("REPAYMENT_YESACCOUNT >=", value, "repaymentYesaccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesaccountLessThan(Double value) {
            addCriterion("REPAYMENT_YESACCOUNT <", value, "repaymentYesaccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesaccountLessThanOrEqualTo(Double value) {
            addCriterion("REPAYMENT_YESACCOUNT <=", value, "repaymentYesaccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesaccountIn(List<Double> values) {
            addCriterion("REPAYMENT_YESACCOUNT in", values, "repaymentYesaccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesaccountNotIn(List<Double> values) {
            addCriterion("REPAYMENT_YESACCOUNT not in", values, "repaymentYesaccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesaccountBetween(Double value1, Double value2) {
            addCriterion("REPAYMENT_YESACCOUNT between", value1, value2, "repaymentYesaccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesaccountNotBetween(Double value1, Double value2) {
            addCriterion("REPAYMENT_YESACCOUNT not between", value1, value2, "repaymentYesaccount");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesinterestIsNull() {
            addCriterion("REPAYMENT_YESINTEREST is null");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesinterestIsNotNull() {
            addCriterion("REPAYMENT_YESINTEREST is not null");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesinterestEqualTo(Double value) {
            addCriterion("REPAYMENT_YESINTEREST =", value, "repaymentYesinterest");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesinterestNotEqualTo(Double value) {
            addCriterion("REPAYMENT_YESINTEREST <>", value, "repaymentYesinterest");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesinterestGreaterThan(Double value) {
            addCriterion("REPAYMENT_YESINTEREST >", value, "repaymentYesinterest");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesinterestGreaterThanOrEqualTo(Double value) {
            addCriterion("REPAYMENT_YESINTEREST >=", value, "repaymentYesinterest");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesinterestLessThan(Double value) {
            addCriterion("REPAYMENT_YESINTEREST <", value, "repaymentYesinterest");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesinterestLessThanOrEqualTo(Double value) {
            addCriterion("REPAYMENT_YESINTEREST <=", value, "repaymentYesinterest");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesinterestIn(List<Double> values) {
            addCriterion("REPAYMENT_YESINTEREST in", values, "repaymentYesinterest");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesinterestNotIn(List<Double> values) {
            addCriterion("REPAYMENT_YESINTEREST not in", values, "repaymentYesinterest");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesinterestBetween(Double value1, Double value2) {
            addCriterion("REPAYMENT_YESINTEREST between", value1, value2, "repaymentYesinterest");
            return (Criteria) this;
        }

        public Criteria andRepaymentYesinterestNotBetween(Double value1, Double value2) {
            addCriterion("REPAYMENT_YESINTEREST not between", value1, value2, "repaymentYesinterest");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNull() {
            addCriterion("ADDTIME is null");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNotNull() {
            addCriterion("ADDTIME is not null");
            return (Criteria) this;
        }

        public Criteria andAddtimeEqualTo(String value) {
            addCriterion("ADDTIME =", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotEqualTo(String value) {
            addCriterion("ADDTIME <>", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThan(String value) {
            addCriterion("ADDTIME >", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThanOrEqualTo(String value) {
            addCriterion("ADDTIME >=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThan(String value) {
            addCriterion("ADDTIME <", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThanOrEqualTo(String value) {
            addCriterion("ADDTIME <=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLike(String value) {
            addCriterion("ADDTIME like", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotLike(String value) {
            addCriterion("ADDTIME not like", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeIn(List<String> values) {
            addCriterion("ADDTIME in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotIn(List<String> values) {
            addCriterion("ADDTIME not in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeBetween(String value1, String value2) {
            addCriterion("ADDTIME between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotBetween(String value1, String value2) {
            addCriterion("ADDTIME not between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddipIsNull() {
            addCriterion("ADDIP is null");
            return (Criteria) this;
        }

        public Criteria andAddipIsNotNull() {
            addCriterion("ADDIP is not null");
            return (Criteria) this;
        }

        public Criteria andAddipEqualTo(String value) {
            addCriterion("ADDIP =", value, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipNotEqualTo(String value) {
            addCriterion("ADDIP <>", value, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipGreaterThan(String value) {
            addCriterion("ADDIP >", value, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipGreaterThanOrEqualTo(String value) {
            addCriterion("ADDIP >=", value, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipLessThan(String value) {
            addCriterion("ADDIP <", value, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipLessThanOrEqualTo(String value) {
            addCriterion("ADDIP <=", value, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipLike(String value) {
            addCriterion("ADDIP like", value, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipNotLike(String value) {
            addCriterion("ADDIP not like", value, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipIn(List<String> values) {
            addCriterion("ADDIP in", values, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipNotIn(List<String> values) {
            addCriterion("ADDIP not in", values, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipBetween(String value1, String value2) {
            addCriterion("ADDIP between", value1, value2, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipNotBetween(String value1, String value2) {
            addCriterion("ADDIP not between", value1, value2, "addip");
            return (Criteria) this;
        }

        public Criteria andTenderTypeIsNull() {
            addCriterion("TENDER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTenderTypeIsNotNull() {
            addCriterion("TENDER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTenderTypeEqualTo(Integer value) {
            addCriterion("TENDER_TYPE =", value, "tenderType");
            return (Criteria) this;
        }

        public Criteria andTenderTypeNotEqualTo(Integer value) {
            addCriterion("TENDER_TYPE <>", value, "tenderType");
            return (Criteria) this;
        }

        public Criteria andTenderTypeGreaterThan(Integer value) {
            addCriterion("TENDER_TYPE >", value, "tenderType");
            return (Criteria) this;
        }

        public Criteria andTenderTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("TENDER_TYPE >=", value, "tenderType");
            return (Criteria) this;
        }

        public Criteria andTenderTypeLessThan(Integer value) {
            addCriterion("TENDER_TYPE <", value, "tenderType");
            return (Criteria) this;
        }

        public Criteria andTenderTypeLessThanOrEqualTo(Integer value) {
            addCriterion("TENDER_TYPE <=", value, "tenderType");
            return (Criteria) this;
        }

        public Criteria andTenderTypeIn(List<Integer> values) {
            addCriterion("TENDER_TYPE in", values, "tenderType");
            return (Criteria) this;
        }

        public Criteria andTenderTypeNotIn(List<Integer> values) {
            addCriterion("TENDER_TYPE not in", values, "tenderType");
            return (Criteria) this;
        }

        public Criteria andTenderTypeBetween(Integer value1, Integer value2) {
            addCriterion("TENDER_TYPE between", value1, value2, "tenderType");
            return (Criteria) this;
        }

        public Criteria andTenderTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("TENDER_TYPE not between", value1, value2, "tenderType");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderIsNull() {
            addCriterion("AUTOTENDER_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderIsNotNull() {
            addCriterion("AUTOTENDER_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderEqualTo(Integer value) {
            addCriterion("AUTOTENDER_ORDER =", value, "autotenderOrder");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderNotEqualTo(Integer value) {
            addCriterion("AUTOTENDER_ORDER <>", value, "autotenderOrder");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderGreaterThan(Integer value) {
            addCriterion("AUTOTENDER_ORDER >", value, "autotenderOrder");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("AUTOTENDER_ORDER >=", value, "autotenderOrder");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderLessThan(Integer value) {
            addCriterion("AUTOTENDER_ORDER <", value, "autotenderOrder");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderLessThanOrEqualTo(Integer value) {
            addCriterion("AUTOTENDER_ORDER <=", value, "autotenderOrder");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderIn(List<Integer> values) {
            addCriterion("AUTOTENDER_ORDER in", values, "autotenderOrder");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderNotIn(List<Integer> values) {
            addCriterion("AUTOTENDER_ORDER not in", values, "autotenderOrder");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderBetween(Integer value1, Integer value2) {
            addCriterion("AUTOTENDER_ORDER between", value1, value2, "autotenderOrder");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("AUTOTENDER_ORDER not between", value1, value2, "autotenderOrder");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderRemarkIsNull() {
            addCriterion("AUTOTENDER_ORDER_REMARK is null");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderRemarkIsNotNull() {
            addCriterion("AUTOTENDER_ORDER_REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderRemarkEqualTo(String value) {
            addCriterion("AUTOTENDER_ORDER_REMARK =", value, "autotenderOrderRemark");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderRemarkNotEqualTo(String value) {
            addCriterion("AUTOTENDER_ORDER_REMARK <>", value, "autotenderOrderRemark");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderRemarkGreaterThan(String value) {
            addCriterion("AUTOTENDER_ORDER_REMARK >", value, "autotenderOrderRemark");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("AUTOTENDER_ORDER_REMARK >=", value, "autotenderOrderRemark");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderRemarkLessThan(String value) {
            addCriterion("AUTOTENDER_ORDER_REMARK <", value, "autotenderOrderRemark");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderRemarkLessThanOrEqualTo(String value) {
            addCriterion("AUTOTENDER_ORDER_REMARK <=", value, "autotenderOrderRemark");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderRemarkLike(String value) {
            addCriterion("AUTOTENDER_ORDER_REMARK like", value, "autotenderOrderRemark");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderRemarkNotLike(String value) {
            addCriterion("AUTOTENDER_ORDER_REMARK not like", value, "autotenderOrderRemark");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderRemarkIn(List<String> values) {
            addCriterion("AUTOTENDER_ORDER_REMARK in", values, "autotenderOrderRemark");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderRemarkNotIn(List<String> values) {
            addCriterion("AUTOTENDER_ORDER_REMARK not in", values, "autotenderOrderRemark");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderRemarkBetween(String value1, String value2) {
            addCriterion("AUTOTENDER_ORDER_REMARK between", value1, value2, "autotenderOrderRemark");
            return (Criteria) this;
        }

        public Criteria andAutotenderOrderRemarkNotBetween(String value1, String value2) {
            addCriterion("AUTOTENDER_ORDER_REMARK not between", value1, value2, "autotenderOrderRemark");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowIdIsNull() {
            addCriterion("FIRST_BORROW_ID is null");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowIdIsNotNull() {
            addCriterion("FIRST_BORROW_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowIdEqualTo(Integer value) {
            addCriterion("FIRST_BORROW_ID =", value, "firstBorrowId");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowIdNotEqualTo(Integer value) {
            addCriterion("FIRST_BORROW_ID <>", value, "firstBorrowId");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowIdGreaterThan(Integer value) {
            addCriterion("FIRST_BORROW_ID >", value, "firstBorrowId");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FIRST_BORROW_ID >=", value, "firstBorrowId");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowIdLessThan(Integer value) {
            addCriterion("FIRST_BORROW_ID <", value, "firstBorrowId");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowIdLessThanOrEqualTo(Integer value) {
            addCriterion("FIRST_BORROW_ID <=", value, "firstBorrowId");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowIdIn(List<Integer> values) {
            addCriterion("FIRST_BORROW_ID in", values, "firstBorrowId");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowIdNotIn(List<Integer> values) {
            addCriterion("FIRST_BORROW_ID not in", values, "firstBorrowId");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowIdBetween(Integer value1, Integer value2) {
            addCriterion("FIRST_BORROW_ID between", value1, value2, "firstBorrowId");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FIRST_BORROW_ID not between", value1, value2, "firstBorrowId");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowScaleIsNull() {
            addCriterion("FIRST_BORROW_SCALE is null");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowScaleIsNotNull() {
            addCriterion("FIRST_BORROW_SCALE is not null");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowScaleEqualTo(String value) {
            addCriterion("FIRST_BORROW_SCALE =", value, "firstBorrowScale");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowScaleNotEqualTo(String value) {
            addCriterion("FIRST_BORROW_SCALE <>", value, "firstBorrowScale");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowScaleGreaterThan(String value) {
            addCriterion("FIRST_BORROW_SCALE >", value, "firstBorrowScale");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowScaleGreaterThanOrEqualTo(String value) {
            addCriterion("FIRST_BORROW_SCALE >=", value, "firstBorrowScale");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowScaleLessThan(String value) {
            addCriterion("FIRST_BORROW_SCALE <", value, "firstBorrowScale");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowScaleLessThanOrEqualTo(String value) {
            addCriterion("FIRST_BORROW_SCALE <=", value, "firstBorrowScale");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowScaleLike(String value) {
            addCriterion("FIRST_BORROW_SCALE like", value, "firstBorrowScale");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowScaleNotLike(String value) {
            addCriterion("FIRST_BORROW_SCALE not like", value, "firstBorrowScale");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowScaleIn(List<String> values) {
            addCriterion("FIRST_BORROW_SCALE in", values, "firstBorrowScale");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowScaleNotIn(List<String> values) {
            addCriterion("FIRST_BORROW_SCALE not in", values, "firstBorrowScale");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowScaleBetween(String value1, String value2) {
            addCriterion("FIRST_BORROW_SCALE between", value1, value2, "firstBorrowScale");
            return (Criteria) this;
        }

        public Criteria andFirstBorrowScaleNotBetween(String value1, String value2) {
            addCriterion("FIRST_BORROW_SCALE not between", value1, value2, "firstBorrowScale");
            return (Criteria) this;
        }

        public Criteria andUserLevelIsNull() {
            addCriterion("USER_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andUserLevelIsNotNull() {
            addCriterion("USER_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andUserLevelEqualTo(String value) {
            addCriterion("USER_LEVEL =", value, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelNotEqualTo(String value) {
            addCriterion("USER_LEVEL <>", value, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelGreaterThan(String value) {
            addCriterion("USER_LEVEL >", value, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelGreaterThanOrEqualTo(String value) {
            addCriterion("USER_LEVEL >=", value, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelLessThan(String value) {
            addCriterion("USER_LEVEL <", value, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelLessThanOrEqualTo(String value) {
            addCriterion("USER_LEVEL <=", value, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelLike(String value) {
            addCriterion("USER_LEVEL like", value, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelNotLike(String value) {
            addCriterion("USER_LEVEL not like", value, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelIn(List<String> values) {
            addCriterion("USER_LEVEL in", values, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelNotIn(List<String> values) {
            addCriterion("USER_LEVEL not in", values, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelBetween(String value1, String value2) {
            addCriterion("USER_LEVEL between", value1, value2, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelNotBetween(String value1, String value2) {
            addCriterion("USER_LEVEL not between", value1, value2, "userLevel");
            return (Criteria) this;
        }

        public Criteria andRatioIsNull() {
            addCriterion("RATIO is null");
            return (Criteria) this;
        }

        public Criteria andRatioIsNotNull() {
            addCriterion("RATIO is not null");
            return (Criteria) this;
        }

        public Criteria andRatioEqualTo(String value) {
            addCriterion("RATIO =", value, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioNotEqualTo(String value) {
            addCriterion("RATIO <>", value, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioGreaterThan(String value) {
            addCriterion("RATIO >", value, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioGreaterThanOrEqualTo(String value) {
            addCriterion("RATIO >=", value, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioLessThan(String value) {
            addCriterion("RATIO <", value, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioLessThanOrEqualTo(String value) {
            addCriterion("RATIO <=", value, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioLike(String value) {
            addCriterion("RATIO like", value, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioNotLike(String value) {
            addCriterion("RATIO not like", value, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioIn(List<String> values) {
            addCriterion("RATIO in", values, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioNotIn(List<String> values) {
            addCriterion("RATIO not in", values, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioBetween(String value1, String value2) {
            addCriterion("RATIO between", value1, value2, "ratio");
            return (Criteria) this;
        }

        public Criteria andRatioNotBetween(String value1, String value2) {
            addCriterion("RATIO not between", value1, value2, "ratio");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rocky_b_tenderrecord
     *
     * @mbggenerated do_not_delete_during_merge Mon May 19 14:13:32 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rocky_b_tenderrecord
     *
     * @mbggenerated Mon May 19 14:13:32 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}