package com.dxjr.base.mapper;

import com.dxjr.base.entity.BaseEMessageRecord;

public interface BaseEMessageRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_record
     *
     * @mbggenerated
     */
    int insert(BaseEMessageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_record
     *
     * @mbggenerated
     */
    int insertSelective(BaseEMessageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_record
     *
     * @mbggenerated
     */
    BaseEMessageRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseEMessageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(BaseEMessageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseEMessageRecord record);
}