package com.dxjr.base.mapper;

import com.dxjr.base.entity.BaseAccountError;

public interface BaseAccountErrorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_error
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_error
     *
     * @mbggenerated
     */
    int insert(BaseAccountError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_error
     *
     * @mbggenerated
     */
    int insertSelective(BaseAccountError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_error
     *
     * @mbggenerated
     */
    BaseAccountError selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_error
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseAccountError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_error
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseAccountError record);
}