package com.dxjr.portal.transfer.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Etransfer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_transfer.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_transfer.TRANSFER_ID
     *
     * @mbggenerated
     */
    private Integer transferId;


    private Integer  subscribeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_transfer.TRANSFER_TANDER_ID
     *
     * @mbggenerated
     */
    private Integer transferTanderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_transfer.SUBSCRIBE_TANDER_ID
     *
     * @mbggenerated
     */
    private Integer subscribeTanderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_transfer.TRANSFER_USER_ID
     *
     * @mbggenerated
     */
    private Integer transferUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_transfer.SUBSCRIBE_USER_ID
     *
     * @mbggenerated
     */
    private Integer subscribeUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_transfer.E_INVEST_NO
     *
     * @mbggenerated
     */
    private String eInvestNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_transfer.AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_transfer.INTEREST_COMP
     *
     * @mbggenerated
     */
    private BigDecimal interestComp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_transfer.COLLECTION_ACCOUNT
     *
     * @mbggenerated
     */
    private BigDecimal collectionAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_transfer.MANAGE_FEE
     *
     * @mbggenerated
     */
    private BigDecimal manageFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_transfer.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_transfer.ADDTIME
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_transfer
     *
     * @mbggenerated
     */
    public Etransfer(Integer id, Integer transferId, Integer subscribeId, Integer transferTanderId, Integer subscribeTanderId, Integer transferUserId, Integer subscribeUserId, String eInvestNo, BigDecimal amount, BigDecimal interestComp, BigDecimal collectionAccount, BigDecimal manageFee, Integer status, Date addtime) {
        this.id = id;
        this.transferId = transferId;
        this.subscribeId = subscribeId;
        this.transferTanderId = transferTanderId;
        this.subscribeTanderId = subscribeTanderId;
        this.transferUserId = transferUserId;
        this.subscribeUserId = subscribeUserId;
        this.eInvestNo = eInvestNo;
        this.amount = amount;
        this.interestComp = interestComp;
        this.collectionAccount = collectionAccount;
        this.manageFee = manageFee;
        this.status = status;
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_transfer.ID
     *
     * @return the value of e_transfer.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_transfer.TRANSFER_ID
     *
     * @return the value of e_transfer.TRANSFER_ID
     *
     * @mbggenerated
     */
    public Integer getTransferId() {
        return transferId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_transfer.TRANSFER_TANDER_ID
     *
     * @return the value of e_transfer.TRANSFER_TANDER_ID
     *
     * @mbggenerated
     */
    public Integer getTransferTanderId() {
        return transferTanderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_transfer.SUBSCRIBE_TANDER_ID
     *
     * @return the value of e_transfer.SUBSCRIBE_TANDER_ID
     *
     * @mbggenerated
     */
    public Integer getSubscribeTanderId() {
        return subscribeTanderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_transfer.TRANSFER_USER_ID
     *
     * @return the value of e_transfer.TRANSFER_USER_ID
     *
     * @mbggenerated
     */
    public Integer getTransferUserId() {
        return transferUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_transfer.SUBSCRIBE_USER_ID
     *
     * @return the value of e_transfer.SUBSCRIBE_USER_ID
     *
     * @mbggenerated
     */
    public Integer getSubscribeUserId() {
        return subscribeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_transfer.E_INVEST_NO
     *
     * @return the value of e_transfer.E_INVEST_NO
     *
     * @mbggenerated
     */
    public String geteInvestNo() {
        return eInvestNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_transfer.AMOUNT
     *
     * @return the value of e_transfer.AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_transfer.INTEREST_COMP
     *
     * @return the value of e_transfer.INTEREST_COMP
     *
     * @mbggenerated
     */
    public BigDecimal getInterestComp() {
        return interestComp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_transfer.COLLECTION_ACCOUNT
     *
     * @return the value of e_transfer.COLLECTION_ACCOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getCollectionAccount() {
        return collectionAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_transfer.MANAGE_FEE
     *
     * @return the value of e_transfer.MANAGE_FEE
     *
     * @mbggenerated
     */
    public BigDecimal getManageFee() {
        return manageFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_transfer.STATUS
     *
     * @return the value of e_transfer.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_transfer.ADDTIME
     *
     * @return the value of e_transfer.ADDTIME
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }


    public Integer getSubscribeId() {
        return subscribeId;
    }

    public void setSubscribeId(Integer subscribeId) {
        this.subscribeId = subscribeId;
    }
}